name: CI

on:
  pull_request:
    branches: [develop, main]
  workflow_call: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (Biome)
        run: npm run lint

      - name: Format check (Biome)
        run: npm run format:check

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Jest)
        run: npm run test:ci

      - name: Build (rslib)
        run: npm run build

      - name: Check publish contents (npm pack dry run)
        run: npm pack --dry-run

  full-matrix:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Jest)
        run: npm run test:ci

      - name: Build (rslib)
        run: npm run build

      - name: Check publish contents (npm pack dry run)
        run: npm pack --dry-run
